/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gwchina_sdk_base_app_AppSecurity */

#ifndef _Included_com_gwchina_sdk_base_app_AppSecurity
#define _Included_com_gwchina_sdk_base_app_AppSecurity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gwchina_sdk_base_app_AppSecurity
 * Method:    getAppToken
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gwchina_sdk_base_app_AppSecurity_getAppToken
  (JNIEnv *, jclass);

/*
 * Class:     com_gwchina_sdk_base_app_AppSecurity
 * Method:    getAppId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gwchina_sdk_base_app_AppSecurity_getAppId
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
